/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1;

//import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login_SignUp
     */
    public Login_SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bdeposit = new javax.swing.JButton();
        Bwithdraw = new javax.swing.JButton();
        BcurrBalance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bdeposit.setText("Deposit");
        Bdeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdepositActionPerformed(evt);
            }
        });

        Bwithdraw.setText("Withdraw");
        Bwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BwithdrawActionPerformed(evt);
            }
        });

        BcurrBalance.setText("Current Balance");
        BcurrBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcurrBalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BcurrBalance)
                    .addComponent(Bwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Bdeposit)
                .addGap(42, 42, 42)
                .addComponent(Bwithdraw)
                .addGap(41, 41, 41)
                .addComponent(BcurrBalance)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BdepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdepositActionPerformed
        // TODO add your handling code here:
        new Fdeposit().setVisible(true);
    }//GEN-LAST:event_BdepositActionPerformed

    private void BwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BwithdrawActionPerformed
        // TODO add your handling code here:
        new Fwithdraw().setVisible(true);
    }//GEN-LAST:event_BwithdrawActionPerformed

    private void BcurrBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcurrBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BcurrBalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login_SignUp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BcurrBalance;
    public javax.swing.JButton Bdeposit;
    public javax.swing.JButton Bwithdraw;
    // End of variables declaration//GEN-END:variables
}
